language: python
cache: pip
python:
  - '3.7'
install:
  - pip install -r requirements_dev.txt
  - python setup.py install
script:
  - make test
after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: pypi
  user: arkottke
  password:
    secure: eIhb+3akjYdSP9aS9ef10WhiD81Mq9TG1p0irsSVwcCa2mUPaKx8Kq/KQ4Bt7Ha+vZKTu9OWedjmrwmzyVmr77NIJTF7I+UCmFDCR8zjMrweQuIlgQ9L/JmNXmmqOdji9Lp94shqzO/hDgwj3w+Fudvek+PCz8x83dYGxtUdi4A=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: arkottke/pygeems
